package com.fitness.aiservice.service;

import com.fitness.aiservice.model.Activity;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Service;

@Service
@Slf4j
@RequiredArgsConstructor
public class ActivityMessageListener {

    private final AIRecommendationService aiRecommendationService;

    @RabbitListener(queues = "activity.queue")
    public void processActivity(Activity activity){
        log.info("Received activity from queue : {}", activity.getId());
//        log.info("Recommendation generated by AI : {}", aiRecommendationService.generateRecommendation(activity));
        aiRecommendationService.generateRecommendation(activity);
    }
}
